project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Yiwen Zhang"
  description: "Political Inequality, Inequality, Computational Social Science"
  navbar:
    background: "#023a75ff"
    foreground: "#ffffffff"
    left:
      - text: Publications
        href: publications.qmd
      - text: Outreach
        href: outreach.qmd
      - text: CV
        href: curriculum.qmd
    right:
      - icon: twitter
        href: https://x.com/Athena_Yiwen
      - icon: envelope
        href: "mailto:y.zhang539@lse.ac.uk"
   

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    toc: true
    linkcolor: black


